version: '2'

services:
  # Configures the Spark Master with Bitnami Spark image
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"  # Spark Master web UI
      - "7077:7077"  # Spark Master port
    networks:
      - lab2_ds_spark_network

  # Set up as Spark Workers connecting to the Spark Master
  spark-worker1:
    image: bitnami/spark:latest
    container_name: spark-worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - lab2_ds_spark_network

  spark-worker2:
    image: bitnami/spark:latest
    container_name: spark-worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - lab2_ds_spark_network

  # Configures the Hadoop Namenode with HDFS cluster details
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    environment:
      - CLUSTER_NAME=hadoop_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9000:9000"  # HDFS namenode RPC port
      - "9870:9870"  # HDFS namenode Web UI
    networks:
      - lab2_ds_spark_network
    volumes:
      # Mounts local folder ./namenode to the container's /hadoop/dfs/name directory
#      - namenode:/hadoop/dfs/name
      - ./namenode:/hadoop/dfs/name

  # Configures the Hadoop Datanode to connect to the Namenode
  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    networks:
      - lab2_ds_spark_network
    volumes:
      # Mounts local folder ./datanode to the container's /hadoop/dfs/data directory
#      - datanode:/hadoop/dfs/data
      - ./datanode:/hadoop/dfs/data

networks:
  # Configures a custom external network
  lab2_ds_spark_network:
    external: true

volumes:
  # Defines volumes for persistent storage of Namenode and Datanode data
  namenode:
  datanode:
